name: Bug Report 🐛
description: Something not working as expected with Chaos Toolkit? Create a Bug Report here.
title: "[project]: "
labels: [bug, needs-triage]
body:
  - type: dropdown
    attributes:
      label: Is this really broken?
      id: dropdown-entry
      description: "You may only select one"
      options:
        - "Yes"
        - "No"
